name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.16'
      - name: Install dependencies
        run: nimble install -y
      - name: Run tests
        run: nimble test -y
